extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss

plugins:
  - stylelint-scss

overrides:
  - files:
    - '*.ts'
    customSyntax: postcss-lit

rules:
  comment-empty-line-before: null
  at-rule-empty-line-before: null
  declaration-empty-line-before: null
  custom-property-empty-line-before: null
  selector-class-pattern: null
  media-feature-range-notation: null

  color-hex-length: long
